= TODO - LEPTOS

== Introduction

This is a simple Todo app, as POC for an Leptos (WASM) application-

The application contains the basic CRUD elements including the create/update handled by a modal window. The application uses the Signal features currently from the nightly build version for an better development experience.

As bonus, the POC uses Tailwind to prettify the application. Trunk includes the Tailwind engine, so no need to install the JavaScript or Standalone version. Also available a small article from my part in French: https://www.sfeir.dev/front/explorer-linnovation-rust-et-webassembly/[]

== Tools

- https://www.rust-lang.org/ (nightly build)

- https://trunkrs.dev/

== Commands

Start the service with live reload for development:

[source,bash]
----
trunk serve --open --port=8080
----

Build a release candidate (artifacts in /dist)

[source,bash]
----
trunk build --release
----

== Running application

The application is deployed on https://oxide-byte.github.io/todo-leptos/[GitHub Pages].

== Next steps

How to continue, perhaps have a look on one of these:

* Router

* Serverside rendering

* Leptos, Islands

* ...